config/routes.rb
Rails.application.routes.draw do
  root to: "people#index"

  resources :people do
    collection {post :import}
  end
end

app/models/affiliation.rb
# == Schema Information
#
# Table name: Affiliation
#
#  id                      :integer          not null, primary key
#  name                    :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Affiliation < ActiveRecord::Base

  has_many :people, through: :person_affiliations
  has_many :person_affiliations, dependent: :destroy

  validates :name, presence: { message: "can't be blank" }

end

app/models/location.rb
# == Schema Information
#
# Table name: Location
#
#  id                      :integer          not null, primary key
#  name                    :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Location < ActiveRecord::Base

  has_many :people, through: :person_locations
  has_many :person_locations, dependent: :destroy

  validates :name, presence: { message: "can't be blank" }

end

app/models/person.rb
# == Schema Information
#
# Table name: People
#
#  id                      :integer          not null, primary key
#  first_name              :string
#  last_name               :string
#  species                 :string
#  gender                  :string
#  weapon                  :string
#  vehicle                 :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Person < ActiveRecord::Base

  has_many :locations, through: :person_locations, dependent: :destroy
  has_many :person_locations, dependent: :destroy
  has_many :affiliations, through: :person_affiliations, dependent: :destroy
  has_many :person_affiliations, dependent: :destroy

  validates :first_name, :species, :gender, presence: { message: "can't be blank" }
  validates :first_name, uniqueness: { scope: [:last_name] }

  def self.search(search)
    search ? where('first_name LIKE :search OR last_name LIKE :search OR species LIKE :search OR gender LIKE :search OR weapon LIKE :search OR vehicle LIKE :search', search: search) : where(nil)
  end

end

app/models/person_affiliation.rb
# == Schema Information
#
# Table name: person_affiliation
#
#  id                  :integer          not null, primary key
#  person_id           :integer
#  affiliation_id      :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

# Join model between person and affiliation
class PersonAffiliation < ActiveRecord::Base

  belongs_to :affiliation
  belongs_to :person, touch: true

  validate :affiliation_must_exists

  def affiliation_must_exists
    errors.add(:affiliation_id, 'The Affiliation ID specified does not exist.') unless Affiliation.exists?(affiliation_id)
  end

end

app/models/person_location.rb
# == Schema Information
#
# Table name: person_location
#
#  id                  :integer          not null, primary key
#  person_id           :integer
#  location_id         :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

# Join model between person and location
class PersonLocation < ActiveRecord::Base

  belongs_to :location
  belongs_to :person, touch: true

  validate :location_must_exists

  def location_must_exists
    errors.add(:location_id, 'The Location ID specified does not exist.') unless Location.exists?(location_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include PeopleHelper
  helper_method :sort_direction, :sort_column

  def index
    @people = Person.search(person_params[:search])
             .order(sort_column + " " + sort_direction)
             .page(params[:page])
             .per(10)
  end

  def import
    begin
      file = person_params[:file]
      file_path = file.path
      Import::Csv::CsvParser.new('Person').parse(file_path: file_path)
      redirect_to root_url, notice: "Data imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  private

  def sort_direction
    %w[asc desc].include?(person_params[:direction]) ? person_params[:direction] : "asc"
  end

  def sort_column
    Person.column_names.include?(person_params[:sort]) ? person_params[:sort] : "first_name"
  end

  def person_params
    params.permit(:id, :first_name, :last_name, :species, :gender, :weapon,
                  :vehicle, :direction, :search, :page, :sort, :file, :utf8,
                  :authenticity_token, :commit)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == self.sort_column || column == 'location' || column == 'affiliation' ? "current #{self.sort_direction}" : nil
    direction = (column == self.sort_column || column == 'location' || column == 'affiliation') && self.sort_direction == "asc" ? "desc" : "asc"
    link_to title, request.parameters.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvDataImporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_people.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= paginate @people %>
<% if @people.count > 0 %>
<table>
  <tr>
    <th><%= sortable "first_name", "First Name" %> </th>
    <th><%= sortable "last_name", "Last Name" %> </th>
    <th><%= sortable "species", "Species" %></th>
    <th><%= sortable "gender", "Gender" %></th>
    <th><%= sortable "weapon", "Weapon" %></th>
    <th><%= sortable "vehicle", "Vehicle" %></th>
    <th><%= sortable "location", "Location" %></th>
    <th><%= sortable "affiliation", "Affiliation" %></th>
  </tr>
<% end %>
  <% @people.each do |person|%>
    <tr>
      <td><%= person.first_name.titleize %></td>
      <td><%= person.last_name.try(:titleize) %></td>
      <td><%= person.species %></td>
      <td><%= person.gender %></td>
      <td><%= person.weapon %></td>
      <td><%= person.vehicle %></td>
      <td><%= person.locations.collect(&:name).join(', ').try(:titleize) %></td>
      <td><%= person.affiliations.collect(&:name).join(', ').try(:titleize) %></td>
    </tr>
    <%end%>
</table>

app/views/people/index.html.erb
<div>
  <div>
    <div>
      <h3>Import CSV Data</h3>
      <%= form_tag import_people_path, multipart: true do %>
          <%= file_field_tag :file, id: "choose-file" %>
          <%= submit_tag "Import CSV", id: "import-submit" %>
      <% end %>
    </div>
  </div>
  <div>
    <div>
      <h3>Search</h3>
      <%= form_tag people_path, method: 'get', id: "people_search" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "", id: "search-input" %>
          <%= submit_tag "Search", name: nil, id: "search-submit" %>
        </p>
      <% end %>
    </div>
  </div>
  </div>  
<div>
  <div>
    <div>
      <h3>Imported Data</h3>
      <div id="people"><%= render 'people' %></div>
    </div>
  </div>
</div>

app/views/people/index.js.erb
$("#people").html("<%= escape_javascript(render("people")) %>");